version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: insider-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insider
    ports:
      - "5430:5432"
    volumes:
      - insider_pg_data:/var/lib/postgresql/data
    networks:
      - insider-network

  redis:
    image: redis:7
    container_name: insider-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - insider-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insider-app
    ports:
      - "3015:3015"
    depends_on:
      - postgres
      - redis
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insider

      REDIS_ADDRESS: redis:6379
      REDIS_PASSWORD:

      PORT: 3015

      NOTIFICATION_CLIENT_BASE_PATH: https://webhook.site/74cdf70d-c2f1-4aa7-9475-91d3bd969803
    networks:
      - insider-network

volumes:
  insider_pg_data:

networks:
  insider-network:
